repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
    args: ['--maxkb=1000']
  - id: check-merge-conflict
  - id: check-json
  - id: check-toml
  - id: check-xml
  - id: debug-statements
  - id: check-docstring-first

- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
    language_version: python3
    args: [--line-length=88]

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    args: [--profile=black, --line-length=88]

- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    args: [
      --max-line-length=88,
      --extend-ignore=E203,W503,E501,
      --exclude=__pycache__,.venv,.git
    ]

- repo: https://github.com/pycqa/bandit
  rev: 1.8.6
  hooks:
  - id: bandit
    args: [-r, core/, server/, cli/]
    exclude: tests/

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.13.0
  hooks:
  - id: mypy
    additional_dependencies: [types-requests]
    args: [
      --ignore-missing-imports,
      --no-strict-optional,
      --warn-return-any,
      --warn-unused-configs
    ]

- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    entry: poetry run pytest tests/ -x -q
    language: system
    pass_filenames: false
    always_run: true
    stages: [pre-commit]

  - id: safety-check
    name: safety-check
    entry: poetry run safety check
    language: system
    pass_filenames: false
    always_run: true
    stages: [pre-push]

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
